dags_user: octaviomtz
dags_uri: https://dagshub.com/octaviomtz/gnn-project.mlflow

weighted_loss: True
weighted_sampler: True
save_model: False
batch_size: 256
epochs: 101
test_ever_epoch: 5
debug_subset: False
model: GNNTrans